sonar.projectKey=Erreur32_MynetworK
sonar.organization=erreur32

sonar.projectName=MynetworK
sonar.projectVersion=0.7.58

# Sources
sonar.sources=src,server
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.test.*,**/*.spec.*,**/coverage/**,src/constants/version.ts,src/main.tsx

# Exclude all sources from coverage (no test suite in this project)
sonar.coverage.exclusions=**/*

# TypeScript
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8
