name: Build & Push Docker image

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: docker

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login git.echosystem.fr -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Build and push image
        run: |
          IMAGE=git.echosystem.fr/erreur32/mynetwork

          # Tag 'latest' + tag par branche
          docker buildx build \
            --platform linux/amd64 \
            --tag "$IMAGE:latest" \
            --tag "$IMAGE:${{ github.ref_name }}" \
            --push \
            .
